# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: Default working directory
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Default working directory: $(System.DefaultWorkingDirectory)"' 

- name: Azure Pipelines Action
  uses: Azure/pipelines@v1.2
  with:
    azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
    azure-pipeline-name: ${{ secrets.AZURE_DEVOPS_VER_PIPELINE }}
    azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

