# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'rtgs-integration-dev'
    subscriptionId: '6c9aba91-2586-46e2-92e6-d6b86f6c6935'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Darren_Deploy_Spike'
    templateLocation: 'URL of the file'
    location: "Ignored_As_Group_Must_Already_Exist"
    csmFileLink: 'https://raw.githubusercontent.com/Darren-Osborne/ver/main/template.json'
    deploymentMode: 'Incremental'