name: Build

on: push 

jobs:
  create-nuget-package:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: dotnet build
        run: |
          dotnet build --configuration Release OsMath/OsMathService/OsMathService.csproj
          dotnet pack -c Release OsMath/OsMathService/OsMathService.csproj --no-build