name: Build

on: push 

env:
  Project_Path: OsMath/OsMathService

jobs:
  create-nuget-package:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: dotnet build
        run: |
          dotnet build --configuration Release ${Project_Path}/OsMathService.csproj
          dotnet pack -c Release ${Project_Path}/OsMathService.csproj --no-build