name: Build

on: push 

env:
  Project_Path: OsMath/OsMathService

jobs:
  create-nuget-package:
    runs-on: ubuntu-latest
    steps: 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_PIPELINES_PAT }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage -h
