name: Build

on: push

env:
  Project_Path: OsMath/OsMathService

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
          azure-pipeline-name: ${{ secrets.AZURE_DEVOPS_VER_PIPELINE_V2 }}
          azure-devops-token: ${{ secrets.AZURE_PIPELINES_PAT }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVOPS_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az devops --help
